default:
  # casinocoinServer: 'ws://192.168.1.4:6006'
  casinocoinServer: 'wss://wst01.casinocoin.org:4443'
  casinocoinServerProduction: 'ws://wsD01.casinocoin.org:7007/'
  database:
    type: 'postgres'
    host: 'apitest.casinocoin.org'
    port: 5432
    username: 'admin'
    password: 'admin'
    database: 'historical'
 