default:
  casinocoinServers: '["wss://wst01.casinocoin.org:4443"]'
  serverPort: 3007
  database:
    type: 'postgres' # postgres or mysql/mariadb
    host: 'localhost'
    port: 5432 # 5432 for postgress, 3306 for mysql/mariadb
    username: 'admin' # postgres
    password: 'admin' # 0000
    database: 'historical' # historical_Proyect
 